parameters:
#    base_test.example.class: Base\TestBundle\Example

services:
#    base_test.example:
#        class: %base_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
