<?php

namespace Base\TestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends EntityRepository
{
    public function getTest($id)
    {
       // ladybug_dump($this);

        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT n FROM BaseTestBundle:Location n WHERE n.id ='.$id);
        return $query;
    }
}