<?php

namespace Base\TestBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Base\TestBundle\Repository\BaseRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends BaseRepository
{
    public function getMethod($id)
    {
        $em = $this->getEntityManager();
        ++$id;
        $query = $em->createQuery('SELECT n FROM BaseTestBundle:Location n WHERE n.id ='.$id);
        return $query;
    }
}